### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by mrechte** [ovh/python-ovh#25]
Hello,

pip install ovh fails on:

 from six.moves import UserString
    ImportError: cannot import name 'UserString'

However six is available:
```
Python 3.5.1 (default, Mar  3 2016, 09:29:07)
[GCC 5.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from six.moves import UserString
>>>
```
`$ uname -a
Linux xxxx 4.5.3-1-ARCH #1 SMP PREEMPT Sat May 7 20:43:57 CEST 2016 x86_64 GNU/Linux`

Full error message:

```
# pip install ovh
Collecting ovh
  Using cached ovh-0.4.2.tar.gz
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python3.5/site-packages (from ovh)
Collecting d2to1==0.2.11 (from ovh)
  Using cached d2to1-0.2.11.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-hhg6m9le/d2to1/setup.py", line 13, in <module>
        setup(**cfg_to_args())
      File "/tmp/pip-build-hhg6m9le/d2to1/d2to1/util.py", line 204, in cfg_to_args
        wrap_commands(kwargs)
      File "/tmp/pip-build-hhg6m9le/d2to1/d2to1/util.py", line 439, in wrap_commands
        for cmd, _ in dist.get_command_list():
      File "/usr/lib/python3.5/site-packages/setuptools/dist.py", line 447, in get_command_list
        cmdclass = ep.resolve()
      File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/usr/lib/python3.5/site-packages/sphinx/setup_command.py", line 23, in <module>
        from sphinx.application import Sphinx
      File "/usr/lib/python3.5/site-packages/sphinx/application.py", line 30, in <module>
        from sphinx import package_dir, locale
      File "/usr/lib/python3.5/site-packages/sphinx/locale/__init__.py", line 15, in <module>
        from six.moves import UserString
    ImportError: cannot import name 'UserString'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-hhg6m9le/d2to1/
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by yadutaf** [comment]
This is definitively strange. Have you tried installing ovh in a fresh virtualenv? It is not generally recommended in Python to mix user installed packages with system managed ones.

**Comment by mrechte** [comment]
Thanks. I tried on another machine (still on Arch) and I did *not* get the problem:

```
# pip install ovh
Collecting ovh
  Downloading ovh-0.4.2.tar.gz (550kB)
    100% |████████████████████████████████| 552kB 1.6MB/s 
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python3.5/site-packages (from ovh)
Collecting d2to1==0.2.11 (from ovh)
  Downloading d2to1-0.2.11.tar.gz
Installing collected packages: d2to1, ovh
  Running setup.py install for d2to1 ... done
  Running setup.py install for ovh ... done
Successfully installed d2to1-0.2.11 ovh-0.4.2
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

It looks like there is some interference with the sphinx package.

However I'll check again with virtualenv tomorrow.

**Comment by yadutaf** [comment]
Good to know! Let me know if you see something we can improve after your tests.

**Comment by mrechte** [comment]
It is OK with virtualenv. Thanks
